huggingface/cookbook

- notebooks/RAG_zephyr_langchain.ipynb
Created a new [HF repo for Cookbook images](https://huggingface.co/datasets/huggingface/cookbook-images), for this reason, updated the link in the notebook.
> Image link update

- README.md
PR updates readme with contribution guidelines.
> Contribution guidelines

- notebooks/en/index.md
> index.md content

- README.md
> link fixed

- notebooks/en/_toctree.yml
- notebooks/en/automatic_embedding_tei_inference_endpoints.ipynb
Minor updates to a notebook, fixed the TOC position
> updates to Derek's notebook

- README.md
Adds scheme to link in README.
* Link was hf.co/learn/cookbook
* Link is now https://hf.co/learn/cookbook
Without scheme link returns 404.
🤗 Ken
> Update link in README.

- .github/pull_request_template.md
- README.md
PR removes @MKhalusova as a default person to tag for a review
> PR removes @MKhalusova as a default person to tag for a review

- .github/pull_request_template.md
- README.md
Adding new reviewers @stevhliu
> Add reviewers

- notebooks/en/pipeline_notus_instructions_preferences_legal.ipynb
Last week, we released a new version of `distilabel ` refactored with breaking changes. At the moment, we  have no room to update it, but we plan to do it. We hope that this small update helps the user.
Fixes # (issue)
Thanks, @merveenoyan and @stevhliu.
> [FIX]: Update package version of tutorial

- notebooks/en/agents.ipynb
Fix an image error that prevents image from showing
> Fix image in agents.ipynb

- notebooks/en/agents.ipynb
- notebooks/en/structured_generation.ipynb
> Add custom LLM engine in agent cookbook

- notebooks/en/_toctree.yml
- notebooks/en/argilla_enterprise.ipynb
- notebooks/en/enterprise_cookbook_argilla.ipynb
- notebooks/en/enterprise_cookbook_overview.md
Adds recipe for data annotation with Argilla to HF Enterprise Cookbook
@stevhliu.
> Argilla enterprise cookbook recipe

- notebooks/en/_toctree.yml
draft PR for testing new section structure discussed [internally here](https://huggingface.slack.com/archives/C06AMDKKDNF/p1716907801911879?thread_ts=1715954541.512919&cid=C06AMDKKDNF)
> new section structure

- notebooks/en/_toctree.yml
- notebooks/en/index.md
- notebooks/en/rag_with_unstructured_data.ipynb
The PR adds a notebook illustrating how to preprocess a few different types of unstructured data into format that can be loaded into a vector store and used for RAG with LangChain.
> Notebook: unstructured data preprocessing for RAG

- notebooks/en/_toctree.yml
@stevhliu as discussed removed division with other libraries
> Remove division with other libraries

- notebooks/en/_toctree.yml
minor fix to notebook section title
> fix section name of argilla notebook

- notebooks/en/enterprise_hub_serverless_inference_api.ipynb
Fixes #118 
Feel free to tag members/contributors who may be interested in your PR.
@merveenoyan @stevhliu @MoritzLaurer
> no need to set env var with token

- notebooks/en/advanced_rag.ipynb
Fixes #120.
I added dependencies installation to solve issues when running using Colab.
> Updated advanced RAG notebook dependencies

- notebooks/en/fine_tuning_code_llm_on_single_gpu.ipynb
Fixes #129.
Updated link to the correct endpoint.
> Restored broken link in Fine-tuning a Code LLM on Custom Code on a single GPU notebook

- notebooks/en/labelling_feedback_setfit.ipynb
Fixes #131.
Temporary workaround to run the notebook as suggested in https://github.com/huggingface/setfit/issues/512
> Patch to enable notebook functionality with a workaround

- notebooks/en/issues_in_text_dataset.ipynb
Fixes #136.
Updated broken link 😄 
> Restored broken link to FAQ

- notebooks/en/enterprise_cookbook_gradio.ipynb
Fixes a couple of left-over issues from https://github.com/huggingface/cookbook/pull/133
@stevhliu.
> Enterprise cookbook gradio fixes

- notebooks/en/agents.ipynb
Fixes #142.
Small typo fixed. 
I'm learning a lot from these notebooks! 😄 Thanks for providing them to the community
> Fixed small typo in agents notebook

- notebooks/en/enterprise_cookbook_gradio.ipynb
Fixes Components link going into 404.
@stevhliu.
> Enterprise cookbook gradio: Fix Component links

- notebooks/en/agents.ipynb
Fixes #146.
I've added the following changes to address the issues:
1. Installation of `langchain-community`.
2. A new cell for adding `SERPAPI_API_KEY`.
3. A cell for HF login.
> Fix minor issues in agents notebook when run using Colab

- notebooks/en/enterprise_cookbook_argilla.ipynb
- notebooks/en/enterprise_cookbook_dev_spaces.md
- notebooks/en/enterprise_dedicated_endpoints.ipynb
- notebooks/en/enterprise_hub_serverless_inference_api.ipynb
Add names to enterprise cookbook recipes as discussed in this [internal thread](https://huggingface.slack.com/archives/C06AMDKKDNF/p1719999721983139)
@merveenoyan and @stevhliu
> add authors to enterprise cookbooks

- notebooks/en/_toctree.yml
- notebooks/en/index.md
- notebooks/en/rag_with_hf_and_milvus.ipynb
- notebooks/zh-CN/_toctree.yml
- notebooks/zh-CN/index.md
- notebooks/zh-CN/rag_with_hf_and_milvus.ipynb
RAG with Hugging Face and Milvus
> rag with hf and milvus

- notebooks/en/enterprise_cookbook_argilla.ipynb
- notebooks/en/labelling_feedback_setfit.ipynb
Due to the release of Argilla 2.0, we updated the two available cookbooks for Argilla.
Images PR: https://huggingface.co/datasets/huggingface/cookbook-images/discussions/23
Thanks in advance, @merveenoyan and @stevhliu!
> Update Argilla cookbooks

- notebooks/en/automatic_embedding_tei_inference_endpoints.ipynb
Fixes #163.
Updated markdown table rendering to also work in Colab  in Colab in [How to use Inference Endpoints to Embed Documents](https://huggingface.co/learn/cookbook/automatic_embedding_tei_inference_endpoints).
> Updated table rendering working in Colab in "How to use Inference Endpoints to Embed Documents"

- notebooks/en/tgi_messages_api_demo.ipynb
Fixes #166.
Solved the following issues:
* Compatibility issue with package versions: letting pip resolve the issue by adding `torchvision torchaudio` to the package upgrade section.
* Added new needed packages since LlamaIndex version has been updated `llama-index-llms-openai-like llama-index-embeddings-huggingface`
* Solved the issue with the API_TOKEN `os.environ["HF_TOKEN"] = HF_API_KEY = getpass.getpass()`
* Solved the rest of the issues with LlamaIndex updating the code.
@merveenoyan and @stevhliu
> Migrating from OpenAI to Open LLMs Using TGI’s Messages API notebook updated

- notebooks/en/semantic_cache_chroma_vector_database.ipynb
> Corrected malformed URL

- notebooks/en/llm_judge.ipynb
> Typos fixed in Using LLM-as-a-judge 🧑‍⚖️ for an automated and versatile evaluation

- notebooks/en/rag_with_hf_and_milvus.ipynb
> Paragraph refined in Build RAG with Hugging Face and Milvus

- notebooks/zh-CN/advanced_rag.ipynb
- notebooks/zh-CN/fine_tuning_code_llm_on_single_gpu.ipynb
- notebooks/zh-CN/rag_evaluation.ipynb
- notebooks/zh-CN/rag_zephyr_langchain.ipynb
> Updated code in the notebooks in Chinese to match English versions

- notebooks/en/_toctree.yml
- notebooks/en/index.md
- notebooks/en/semantic_reranking_elasticsearch.ipynb
👋 Hi @merveenoyan and @stevhliu!
We (Elastic) are big fans of the cookbook. We would like to add this recipe to demonstrate how to combine Hugging Face models with Elasticsearch.
I've tested the steps and removed what I think are any unnecessary cell outputs. Let me know what you think!
ℹ️ I created a new "Search Recipes" section in `_toctree.yml` because I wasn't sure where to fit this one.
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://github.com/huggingface/cookbook/blob/672d857f2e33ac0e0cf560b82b6d050df6fdd87f/notebooks/en/semantic_reranking_elasticsearch.ipynb)
> Add Elasticsearch semantic reranking recipe

- notebooks/en/multiagent_web_assistant.ipynb
Fixes #193
@merveenoyan and @stevhliu
> `Have several agents collaborate in a multi-agent hierarchy 🤖🤝🤖` notebook improvements

- notebooks/en/agent_text_to_sql.ipynb
> Added missing HF login cell in `Agent for text-to-SQL with automatic error correction` notebook

- .github/workflows/build_documentation.yml
- .github/workflows/build_pr_documentation.yml
- notebooks/tr/_toctree.yml
- notebooks/tr/index.md
Hello 👋 This PR presents the Turkish translation of [Fine-Tuning a Semantic Segmentation Model on a Custom Dataset and Usage via the Inference API](https://huggingface.co/learn/cookbook/semantic_segmentation_fine_tuning_inference) and adding initial index and _toctree.yml as well. 
> docs(translation): 🌐 add Turkish translation for semantic_segmentation_fine_tuning_inference.ipynb and initial content

- README.md
> Add new cookbook org

- notebooks/en/agent_rag.ipynb
Fixes #231.
I've tested the notebook with these changes and the final results changed a little:
I know that the output should go in the opposite direction and that the final results may vary but it still looks a bit off to me. What do you think? 
cc @aymeric-roucher 
> Updated Agentic RAG recipe

- notebooks/tr/_toctree.yml
Translation of `Fine-Tuning Object Detection on a Custom Dataset 🖼, Deployment in Spaces, and Gradio API Integration` DETR cookbook
I also made some small adjustment in the cookbook I will would like to apply those to main en version of notebook too.
- Fixing Dependencies List (useful for local runs)
- Fixing numbering order in cookbook
- Create `requirements.txt` via command and write dependencies into file with echo to have useful commands instead of commentary code block
cc @merveenoyan
> docs(translation): 🌐 add Turkish translation for fine_tuning_detr_custom_dataset

- notebooks/en/multimodal_rag_using_document_retrieval_and_smol_vlm.ipynb
> Updated `Smol Multimodal RAG`installation instructions - new colpali package version released

- notebooks/en/advanced_rag.ipynb
- notebooks/en/rag_evaluation.ipynb
This PR fixes some small typos in some RAG cookbooks.
Feel free to tag members/contributors who may be interested in your PR.
cc: @merveenoyan and @stevhliu for reviews, thank you!
> Small fixes to Advanced RAG cookbook

- notebooks/en/fine_tuning_granite_vision_sft_trl.ipynb
Fixed issue with granite-vision QLORA training and made it the default
@merveenoyan and @stevhliu
> Fixed issue with granite-vision QLORA training and made it the default
